### ISSUE TITLE
CCLI: Login Command Button

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/cryptopus#383]
Move the ccli login command button into the navbar. When the user clicks on it, it should copy the login command with the correct token into the clipboard:

If the user has no standard ccli user, simply create one as the button is pressed

Similar to openshift login command:

![image.png](https://images.zenhubusercontent.com/60182665657f47903bf9cfb6/2fb1d038-71d8-4d02-b692-72bf386912a6)

# TODO:
- [x] Read through the WIP Progress Branch of Mio linked below. However you probably should start over on the main branch as Mio's branch is quite behind.
## Backend
- [x] new endpoint /api/api_users/ccli_token:
  - [x]  looks up ccli user for current_user
  - [x] if none found, create one
  - [x] renew ccli user
  - [x] respond with renewed token and username

## Frontend
- [x] Add Button to navbar including action
  - [x] Looks up ccli user token (/api/api_users/ccli_token)
  - [x] copy login command to clipboard
    - Login command: `cry login #{Base64(#{api_user.username}:#{renewed_token})}@#{cryptopus_url}`

- [ ] And of course add tests :grin:

**Comment by miosidler** [comment]
Git branch: https://github.com/puzzle/cryptopus/tree/feature-383-ccli-login-command-button
