### ISSUE TITLE
TECH: system specs fail during github action build

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#503]
system specs do fail after 6h during Cryptopus CI build.

all tests are failing with the same error:

```
31) UpdatePasswordModal shows error message when inputs are incorrect
      Got 0 failures and 2 other errors:

      31.1) Failure/Error: raise ActionController::RoutingError, 'Not Found' if request.path == url_handler.redirect_to

            ActionController::RoutingError:
              Not Found
            # ./app/controllers/redirected_routes_controller.rb:13:in `redirect'
            # ------------------
            # --- Caused by: ---
            # Net::ReadTimeout:
            #   Net::ReadTimeout with #<TCPSocket:(closed)>
            #   ./spec/support/system_helpers.rb:13:in `login_as_user'

      31.2) Failure/Error: (io = @io.to_io).wait_readable(@read_timeout) or raise Net::ReadTimeout.new(io)`
```

The problem seams to be present since Jun 18, 2021. https://github.com/puzzle/cryptopus/runs/2854729654?check_suite_focus=true

# ToDo

- [x] update webdrivers gem
- [x] fork repo and check if cache is causing problem: same problem on fork
- [x] run 'bundle exec rake nightly:e2e --trace' locally: works
- [x] make sure frontend prepare is always executed

**Comment by mtnstar** [comment]
fixed
