### ISSUE TITLE
TECH: Upgrade EmberJS to newest LTS Version

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#511]
Upgrade EmberJS and all possible JS dependencies

Upgrade to 3.28.8 is blocked due to: https://github.com/emberjs/ember.js/issues/19432 -> investigating

# ToDo

- [ ] Upgrade EmberJS to newest LTS
- [ ] Upgrade all JS dependencies to newest version where possible
- [ ] Check that all security issues are fixed with this upgrade
- [ ] Make sure docker development setup is still working
- [ ] Make sure system specs are working

**Comment by njaeggi** [comment]
Cant upgrade Ember to latest LTS because of the issue linked above. ember-popper is causing problems. its used for ember-bootstrap. when upgrading ember-bootstrap ember-auto-import needs upgrades too, when updated 7 tests on localhost:4200/tests fail.
