### ISSUE TITLE
TECH: Upgrade to Ruby 3.0, Rails 7.0

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#512]
Upgrade Cryptopus:

- Ruby 3.0
- Rails 7.0

# Tech-Spec

- https://github.com/puzzle/cryptopus/blob/master/docker-compose.yml
- https://github.com/puzzle/cryptopus/blob/master/Dockerfile
- https://github.com/puzzle/cryptopus/blob/master/.ruby-version
- https://github.com/puzzle/cryptopus/blob/master/Gemfile
- https://github.com/puzzle/cryptopus/tree/master/config/docker

# ToDo

- [ ] Test if Cryptopus runs with Ruby 3.0
- [ ] Upgrade Docker Development Setup
- [ ] Upgrade Docker Image
- [ ] Use bundle update to update all Ruby Gems
- [ ] Update Rails to 7.0 https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
- [ ] Remove all deprecations (deprecation warnings)
- [ ] Make sure all specs are passing
- [ ] Update Docker File and verify build https://quay.io/repository/puzzle/cryptopus?tab=builds
- [ ] Update Openshift Integration -> Done by Puzzle
