### ISSUE TITLE
TECH: Concept for MySQL to PostgreSQL migration

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#515]
in production, we're using MySQL as DB. 
like in other projects we would like to switch to PostgreSQL. 

Goal of this issue is to create a concept on how to switch from MySQL to Postgresql

# ToDo
- [x] PoC: try to run development setup with postgresql
- [x] Create Issue for updating development setup (default development setup should run with postgresql)
  - https://github.com/puzzle/cryptopus/blob/master/docker-compose.yml
<del> - [ ] Create Issue for creating migration rake tasks (db:dump, db:import) <del>
- [x] Create Issue for using pg_search instead of plain sql search if postgresql (making sure not to break the current search implementation)
  -  https://github.com/puzzle/cryptopus/blob/master/app/presenters/teams/filtered_list.rb

**Comment by lkleisa** [comment]
I created a conception for the migration [here](https://codimd.puzzle.ch/qKQ9PTSaT5il9pQeq0oVdQ#). I didn't start with the issues for rake tasks and using pg_search instead of plain sql search

**Comment by lkleisa** [comment]
I created a conception with infos and a way to do: https://codimd.puzzle.ch/qKQ9PTSaT5il9pQeq0oVdQ?view
Issue for migration: https://app.zenhub.com/workspaces/puzzle-bbt-6020f3723c433b000e12ff51/issues/puzzle/cryptopus/102
Issue for pg_search: https://app.zenhub.com/workspaces/puzzle-bbt-6020f3723c433b000e12ff51/issues/puzzle/cryptopus/103

**Comment by lkleisa** [comment]
Final issue for completing this migration:

https://app.zenhub.com/workspaces/puzzle-bbt-6020f3723c433b000e12ff51/issues/puzzle/cryptopus/598
