### ISSUE TITLE
ENCRYPTABLES: Refactor Cryptutils

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#521]
currently, there's only one class responsible for all encryption tasks. 

[CryptUtils](https://github.com/puzzle/cryptopus/blob/master/lib/crypt_utils.rb)

So there's Password Hashing, RSA and AES related tasks all together in this class.

# ToDo

- [x] Create a concept for spliting all these different tasks into different classes
- [x] Make it possible to introduce newer algorithms in the future but still remain the existing ones
- [x] Create Issue with the results of this conception for doing the refactoring (See https://github.com/puzzle/cryptopus/issues/523)
