### ISSUE TITLE
ENCRYPTABLES: Access and Change History

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#525]
# 1. Access / Change log
to make access to stored credentials and other sensitive content more transparent, there should be an access and change log.
so on every encryptable entry it's clear who access what and when. 

# 2. Previous values / History
it should be possible to view/access previous values of username, password and maybe also other fields like encryptable description. 
original feature request #311 

# ToDo
- [x] Make your-self familiar with the encryptables data structure and how encryption works in cryptopus (see wiki)
- [x] Evaluate gems for Access / Change Log (paper trail, ...)
- [x] Create concepts for the two features including mockups for frontend changes
- [x] Would be nice to show last couple of credentials accessed by the user on dashboard
- [x] Consider also a 'My Activity' page at user profile and list the user's activity there
- [x] Incorporate UX for mockups etc.
- [ ] Identify packages to implement 1. Access / Change Log and create one epic and needed issues for implementation
- [ ] Identify packages to implement 2. Previous Values / History and create one epic and needed issues for implementation
- [ ] Based on the 2 above points create Issues
- [x] Proof of concept (hack a little)

**Comment by lkleisa** [comment]
I finished the mockups, which @njaeggi started. Included them in the codi file with the conception, this codi is not finished yet:
https://codimd.puzzle.ch/zHeRv4RGQamXpT72UHqkrA?both

**Comment by lkleisa** [comment]
All mockups are here in the figma project:
https://www.figma.com/file/mlfFr7F6qgAkbdmtTJW7AY/Changelog?node-id=0%3A1

**Comment by lkleisa** [comment]
Basically finished, but we have a meeting with Phillip from UX tomorrow, for the mockups.

**Comment by lkleisa** [comment]
Finished the conception with updated mockups and information about the implementation. Add some text, what we need to add (controller, table in db, ...). Full conception is here:
https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md
