### ISSUE TITLE
Encryptables: Encryptable::File upload

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#531]
Files need to be added via the add option within the credential show.

# ToDo
- [ ] Check where to put "+" action to upload Files
- [ ] Add Actions
- [ ] Check/Fix Backend endpoints
- [ ] Create Integration and Unit tests
