### ISSUE TITLE
TECH: remove ember-cli-eslint and provide other method for linting

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#535]
according to: https://github.com/emberjs/rfcs/blob/master/text/0121-remove-ember-cli-eslint.md, ember-cli-eslint is deprecated.

# ToDo
- [ ] Find a new way for linting
- [ ] Remove deprecated ember cli addon
- [ ] Make sure linting is done in github action builds
- [ ] Update developer documentation
