### ISSUE TITLE
TECH: Upgrade frontend dependencies, remove deprecation warnings

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#536]
we want to update all frontend dependencies to get rid of all security issues: https://github.com/puzzle/cryptopus/security/dependabot
we also want to eliminate all frontend deprecation warnings

some libs were already upgraded with: https://github.com/puzzle/cryptopus/commit/4d48f649b94de4a284b4414ef79e72b531507143

# ToDo
- [x] add changelog entry for version 4.1 (CHANGELOG.md)
- [x] Create a list of all used frontend libs/addons in frontend/README.md
  - the list should include the name, version and what the lib is used for
  - this should make it more clear what addons we're using
- [x] try to upgrade every lib to latest version possible
- [x] try to remove unused/unnecessary libs
- [x] make sure the update does not break anything (manual and automated testing)
- [ ] try to remove all deprecation warnings displayed in browser console

**Comment by lkleisa** [comment]
I added all the dependencies to the list in the codi file. Add for each name, version and if it was possible, for what we need it or what it is used for generally

**Comment by lkleisa** [comment]
> List for all used Dependencies https://codimd.puzzle.ch/0t3Tf0YISkKhldHsh41-Hw#
> 
> Dependencies to check:
> 
>     * text-security
> 
>     * @ember/jquery
> 
>     * @ember/optional-features
> 
>     * @ember/render-modifiers
> 
>     * bootstrap
> 
>     * ember-auto-import
> 
>     * ember-autofocus-modifier
> 
>     * ember-bootstrap
> 
>     * ember-bootstrap-power-select
> 
> 
> The rest is already tested and upgraded

Tried to check these dependencies, but had always an error. Couldn't test seriously, because of that, I didn't pushed anything

**Comment by njaeggi** [comment]
upgraded and removed some dependencies that were causing security issues. All high and critical rated issues that are possible to solve should already be solved. Haven't looked at the others with lower rating.
