### ISSUE TITLE
ENCRYPTABLES SHARING: Personal Team for User

### ISSUE THREAD

**Issue by njaeggi** [puzzle/cryptopus#559]
The idea of this feature is to create a personal for every user. This personal Team can be used to store the users personal credentials and also for the incoming encryptables.

# Mockup
 ### Personal Team
![Dashboard](https://raw.githubusercontent.com/puzzle-bbt/kon-cryptopus-messages/master/dashboardWithPersonalTeam.png)
### Inbox Folder
![Inbox](https://raw.githubusercontent.com/puzzle-bbt/kon-cryptopus-messages/master/PersonalTeamOpened.png)
### Shared Credentials
![Encryptable in your Inbox](https://raw.githubusercontent.com/puzzle-bbt/kon-cryptopus-messages/master/EncryptableInInbox.png)

# Todo

- [x] create new db migration
  - users: personal_team_id, int, null: true
  - create personal-team for every existing user
- [x] add has_one :personal_team relation to model: User
- [x] make sure personal team gets created for new users
- [x] adjust TeamsController to include personal team at first position
- [x] adjust TeamPolicy
  - do not allow to update personal team
  - do not allow to add team members to personal team
  - do not allow to delete personal team
  - allow to enable api users for personal team
- [x] mark personal team in frontend with different color
- [x] disable all unavailable functions for personal team in UI
- [x] translate personal team name (Personal / Persönlich)

**Comment by njaeggi** [comment]
Almost finished, only thing left todo are the Translations and some more system tests to test the UI.

**Comment by njaeggi** [comment]
Todo list to implement STI
- [ ] db migration add column type
- [ ] adjust tests for model
- [ ] adjust test for controller
- [ ] adjust relations between models
- [ ] fix seeding error
