### ISSUE TITLE
ENCRYPTABLE SHARING: Extend Encryptables Controller for File sharing

### ISSUE THREAD

**Issue by njaeggi** [puzzle/cryptopus#561]
Adjust the post create action to handle an additional receiver id param to share files.

### Conception
- https://codimd.puzzle.ch/tozsq7r-STCJ29iqsMbS9w#

# Todo
- [x] Implement specs for transfer domain class
- [x] Implement review feedback for transfer domain class
  - [x] Create personal Team inbox folder if nonexistent
- [x] Edit EncryptablePolicy create?
  - [x] true when user is logged in and receiver is not API User or the sender himself
- [x] Write new Specs for Sharing Feature in EncryptableControllerSpec
  - [x] Make sure that it is impossible to send to api-users and nonexistent recipients
  - [x] Create two sets of permitted attrs. Use one according situation.
  - [x] Create new flash message if file was sent successfully or unsuccessfully
- [x] Use transfer domain class in Encryptable Controller
