### ISSUE TITLE
Access- and changelog: MINIMAL

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#564]
## Access and changelog in the minimal version

If multiple members work with one team in cryptopus, it can quickly become confusing. For example, someone updates a password for an account, but someone has to use the old password. Because of this, it would be useful to have an access- and changelog, where you can see, who updated what with which value.

To access the page, there would be a new tab with the text log. In the minimal edition, there would be the username from the person, who changed something in this encryptable and the date and time from the change. 

A full conception with mockups and informations for the implementation you find here: [Access- and changelog conception](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md)

### ToDo

- [ ] Add all required elements to use [papertrail](https://github.com/paper-trail-gem/paper_trail) in cryptopus. You can see in the readme from paper trail, what you need to add to our project. More informations are also in the conception, [Paper trail technology](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#technology).
- [ ] Add [the new log_controller](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#new-controller).
- [ ] Add [the new request-url](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#new-request).
- [ ] Add the code for the table on the log page in the frontend 
- [ ] Add the data, which you fetch with the new request, to the table 
- [ ] Decide, if we want to use pagination, if you think yes, consider [which method we want to use](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#pagination) and add the required code.
