### ISSUE TITLE
Access- and changelog: EPIC

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#566]
## Access and changelog in the epic version

This version of the access- and changelog page is based on [the minimal version](https://github.com/puzzle/cryptopus/issues/564) and [the deluxe version](https://github.com/puzzle/cryptopus/issues/565).

I recommend you, to read [the full conception](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md) first, so that you know what we want to do with this story.  

It would be useful, if we could filter the logs with the changed attribute. We would make this with a drop down with the different attributes which could change. More, we have here a column with the changed attribute.

We displayed in the deluxe version already the old and the new value of an attribute, so it's not difficult to write which value was changed. 

Please use basically the same design  as we designed it in the mockups. They are reviewed with UX and have a similar design as the whole application.
[Mockup for the epic edition](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#log-page-epic-example)

### ToDo

- [ ] Decide, how we could make a filter drop down. It can be that there are multiple libraries, which solve this step. 
- [ ] Add the dropdown with all attributes, which possible could change and show only the data in the log which we set with the filter.  
- [ ] Make a new attribute "Changes" and add the changed value to this column.
