### ISSUE TITLE
Access- and changelog: ULTRA

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#567]
## Access and changelog in the ultra version

This version of the access- and changelog page is based on [the minimal version](https://github.com/puzzle/cryptopus/issues/564), [the deluxe version](https://github.com/puzzle/cryptopus/issues/565) and [the epic version](https://github.com/puzzle/cryptopus/issues/566).

I recommend you, to read [the full conception](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md) first, so that you know what we want to do with this story.  

This is one of the most detailed version of the feature, which we could make. The user can define somewhere in the settings (Profile), his default filter. This filter would be active, if the user opens a new log page. In this version, he could also search for specific users or a date. Of course, the user can change the filter with the dropdown menu.

Please use basically the same design  as we designed it in the mockups. They are reviewed with UX and have a similar design as the whole application.
[Mockup for the ultra edition](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md#log-page-ultra-example)

Always run the E2E-tests if you change something in the frontend, run the backend-tests if you change something in the backend and **test always manually**

### ToDo

- [ ] Add a new drop down somewhere in the settings from the profile, where the user can set a default filter for the attributes on the log page. 
- [ ] Activate the filter always when the user opens a log page.
- [ ] Search a useful tool for the search for users or a date. 
- [ ] Implement the found search method in cryptopus.
