### ISSUE TITLE
LOG: Personal activity log

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#568]
The idea of this feature is to log all personal changed or accesses to encryptables.  

![Mockup minimal version](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/images/PersonalActivityLogMinimal.png?raw=true)
![Top bar drop down](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/images/TopBarDropDown.png?raw=true)

This feature is based on: [Access- and changelog conception](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md) and previous [Issue 564](https://github.com/puzzle/cryptopus/issues/564)

Always run the E2E-tests if you change something in the frontend, run the backend-tests if you change something in the backend and test always manually

## ToDo

- [x] Add new controller API::PersonalLogsController, action: index 
  - [x] Fetch personal versions entries
  - [x] Create new serializer PersonalLogSerializer: event, created_at, item_id, item_name (team/folder/encryptable/name)
  - [x] PaperTrail::Version.where ... to fetch all personal entries
  - [x] make sure to includes teams, folders to avoid n+1 queries
  - [x] Add controller specs
  - [x] Add new route /api/personal_logs
- [x] Add model, adapter to frontend
- [x] Add components and new templates 
  - [x] Add table and columns
  - [x] add link to encryptable
- [x] Add frontend tests
- [x] Add system specs
- [x] Add new menu entry to top bar drop down (above profile)

**Comment by MuStAgEDelta** [comment]
frontend is prepared 
Spec tests are prepared 
Waiting for issue #564 for the backend stuff
