### ISSUE TITLE
ENCRYPTABLES: RECRYPT view

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#594]
In order to present a view of what's happening in the backend while recrpyts are in progress, an additional feature needs to be add to present visual updates to the user. We decided to implement this feature in form of a loading spinner.

Evaluate implementation with the spinner package in advance. 
- [x] Check spinner package (https://www.npmjs.com/package/ember-loading) 

Spinner can be done by css. Some examples are displayed here: https://loading.io/css/

# ToDo
- [x] Add loading spinner to view
- [x] Use it everywhere things are getting loaded
- [x] Make sure spinner is displayed correctly
