### ISSUE TITLE
ENCRYPTABLES: RECRYPT controller

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#595]
As of today, the recrypt should be triggered on team show. Does one team not have the latest algorithm set and is not being recrypted, then it shall be recrypted. This should be done by wiring-up the new domain class, where the logic is contained.

# ToDo
- [x] Make new Check in `Teams#show` to check if latest algorithm is in use
- [x] If not, recrypt the given team with `Crypto::Recrypt` Class
- [x] If latest algorithm is in use, nothing should be changed
