### ISSUE TITLE
ENCRYPTABELS: CUSTOM ATTRS change UI

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#596]
In order to create the feature of adding custom attrs, some frontend changes are needed.

# ToDo
- [ ] Alter current UI style to match conception ([Conception UI](https://github.com/puzzle-bbt/kon-cryptopus-encryptables/blob/master/1_konzeption/1.2_ui_changes.md#neu-erstellen))
- [ ] Display lock in textfield if field not encrypted
- [ ] Add functionality for different custom attrs
