### ISSUE TITLE
TECH: Add support for postgresql and pg search

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#598]
cryptopus currently supports mysql and sqlite as dbms. 
we want to add postgresql support and also use pg search instead of plain SQL queries for searching.

# ToDo

- [x] Make sure db migrations work with postgresql (use binary instead of blob) (merged to master, released with 4.4)
- [x] Add a docker compose config with postgresql in config/docker/postgresql-development, make sure cryptopus works with postgresql (merged to master, released with 4.4)
- [ ] Implement current filtered list to support pg search
  - if postgresql, then use pg search
  - if other dbms, use sql for search (current implementation)
- [ ] Create a manual for switching from mysql to postgresql

# Tech-Spec
- https://github.com/puzzle/cryptopus/blob/master/app/presenters/teams/filtered_list.rb
- https://github.com/hitobito/hitobito/tree/master/app/domain/search_strategies
  - for some inspiration for naming, maybe search strategy is a good term
  - it might make sense to extract search logic to own class

**Comment by lkleisa** [comment]
# MySQL to PostgreSQL migration conception

In cryptopus production, we currently use MySQL as database. We would like to switch to PostgreSQL, like in other projects. 

PostgreSQL has some advantages, which we want to use.

First, we add PostgreSQL in our Gemfile:
```
gem 'pg'
```

We need to change some things in our config/database.yml file. We change part with "base: &generic" with the following:
```
base: &generic
  adapter: postgresql
  pool: 5
  encoding: utf8
<% %w(host port username password).each do |option| %>
  <% value = ENV["RAILS_DB_#{option.upcase}"] %>
  <%= "#{option}: #{value}" if value.present? %>
<% end %>
```
If you want to use mysql, only rename postgresql to mysql2.

Because we use now postgresql, we need to change the data type "blob" to binary in the migrations. This would be in 20200612084506_change_file_column_size.rb:
```
class ChangeFileColumnSize < ActiveRecord::Migration[6.0]
  def up
    change_column :file_entries, :file, :binary, size: :medium
  end

  def down
    change_column :file_entries, :file, :binary
  end
end
```

### Local test
For testing the change from mysql to postgresql, we created 2 local docker containers. Maybe, we need to change some things, so that it works fine in production.

#### Postgres container
Our new postgres docker container would look like this (cryptopus/docker-compose.yml):
```
cryptopus-postgres:
    image: postgres:12.10
    container_name: cryptopus-postgres
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - cryptopus-postgres:/var/lib/postgres
```
The rails container gets some new environment variables: 
```
environment:
      RAILS_DB_ADAPTER: 'postgresql'
      RAILS_DB_HOST: 'cryptopus-postgres'
      RAILS_DB_NAME: 'cryptopus-postgres-db'
      RAILS_DB_USERNAME: 'postgres'
      RAILS_DB_PASSWORD: 'password'
      RAILS_DB_PORT: 5432
```

#### MySQL container
This would be the mysql container: 
```
cryptopus-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: cryptopus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - cryptopus-mysql:/var/lib/mysql
```
For this container, the rails container needs the following environment variables:
```
environment:
      RAILS_DB_ADAPTER: 'mysql2'
      RAILS_DB_HOST: 'cryptopus-mysql'
      RAILS_DB_NAME: 'cryptopus-mysql-db'
      RAILS_DB_USERNAME: 'root'
      RAILS_DB_PASSWORD: 'example'
      RAILS_DB_PORT: 3306
```

### Migration
We took the information for the following steps for the migration from mysql to postgres from this guide:

https://hlcfan.github.io/migrate-from-mysql-to-postgresql-rails.html

First, we back up our mysql db (this step is not essential):
```
docker exec MySQLContainerID /usr/bin/mysqldump -u root --password=example cryptopus-db > backup.sql
```
After that, we install the [pgloader tool package](https://github.com/dimitri/pgloader)
```
sudo apt-get install pgloader
```
We create a migration.load file with the following content:
```
LOAD DATABASE
  FROM mysql://root:example@localhost/cryptopus-db
  INTO postgresql://postgres:password/cryptopus-db
```
We need to add a user to the postgres container:
1. Enter the container:
```
docker exec -it ContainerID bash
```
2. Log in with postgres user (password: example):
```
psql -U postgres -W
```
3. Create new user:
```
create user testUser with password 'example';
```
4. Grant access to testUser:
```
alter user testUser with superuser;
```
For the pgloader, we need the ip from the 2 containers:
```
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ContainerID
```
Finally, we can run the pgloader:
```
pgloader mysql://root:example@MySQLContainerIP/cryptopus-db postgresql://testUser:example@PostgesContainerIP/cryptopus-db
```
Now we migrated from MySQL to postgresql

### Pg_Search 
We want to use pg_search instead of plain sql search 
https://github.com/Casecommons/pg_search#searching-using-different-search-features

We add the gem to our Gemfile:
```
gem 'pg_search'
```
We add the following code in all our models, which we want to search for over the search bar. In our case, this would be team, encryptable and folder.
```
include PgSearch::Model
```
More, we explain, what we want to track. In our case, this would be name and description.
```
pg_search_scope :search_starts_with,
   against: [:name, :description],
   using: {
     tsearch: { prefix: true }
   }
```
Now we're able to search for a name or a description:
```
Encryptable.search_starts_with("Cole")
```

We add a new class "QuerySearch" in app/presenters/teams. This class handles, if we use pg_search or plain sql. We add to the FilteredList class a new method for getting the db name:
```
def database_name
    Rails.configuration.database_configuration[Rails.env]["database"]
end
```
In class Teams::QuerySearch, there is in the initializer a check, which db we use. 
```
if database_name == "cryptopus-postgres-db"
```
If we use postgres, the function with pg_search is called, else we have the current method with sql search (teams/filtered_list.rb: line 55) 

### Useful links:
#### Migration
1) https://github.com/dimitri/pgloader/issues/1308
2) https://pgloader.readthedocs.io/en/latest/tutorial/tutorial.html#migrating-from-mysql-to-postgresql
3) https://www.digitalocean.com/community/tutorials/how-to-migrate-mysql-database-to-postgres-using-pgloader

#### Pg_search
1) https://www.mintbit.com/blog/searching-made-easy-with-pg-search-gem-in-ruby-on-rails
2) https://github.com/Casecommons/pg_search#searching-using-different-search-features

### Problems
- Sometimes, there was an error after changing the running database from mysql to postgres. Then it helped to remove all data from docker
    - docker-compose down
    - docker volume prune
    - docker image prune
    - docker system prune -a
- If you want to run mysql db again, don't forget to change postgresql to mysql2 in config/database.yml file
