### ISSUE TITLE
ENCRYPTABLES: CUSTOM ATTRS: Changes to frontend #2

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#634]
In order to get the frontend working with the backend adjustments, some changes in the UI are needed.

![encryptables_create.png](https://images.zenhubusercontent.com/5faa4de0399793e6e36980fc/0fb3c9a2-1eb5-4ee2-a55a-32304daea039)

# ToDo

- [x] Change form to new mockup
- [x] add locks for encrypted fields
- [x] let fields be removed and added back
- [x] adjust show encryptable
- [x] adjust encryptable row
- [x] imrpove copy blank value handling
- [x] add new field component
- [x] adjust format-cleartext helper
- [x] add translations
- [x] adjust frontend model
- [x] add new model attribute used attrs for row
- [x] fetch encryptable for edit in row
- [x] change styling of row component
- [x] load form field dynamically
- [ ] Auf Integrations extensiv testen
- [ ] @mtnstar mit Proddaten testen bevor prod release
