### ISSUE TITLE
ENCRYPTABLE SHARING: Display number of unread file transfers

### ISSUE THREAD

**Issue by luca-bruegger** [puzzle/cryptopus#638]
When sharing a file or an encryptable with another user, it will land in receiver user's inbox folder (in personal team). It would be nice if the receiver sees, that he received a new file or encryptable. 

### ToDo
- [ ] If personal team, get number of unread transfered encryptables (count encryptables inside INBOX folder with present transfer_password), use SQL select count
- [ ] Adjust TeamSerializer to serialize mentioned field
- [ ] Adjust frontend model and component
- [ ] Display new badge on team and inbox folder
