### ISSUE TITLE
ENCRYPTABLE SHARING: Finish full feature 

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#657]
We started with the feature for Encryptable::File sharing in these stories: 
Controller: #561 
UI: #611 
This is the branch with the latest version: https://github.com/puzzle/cryptopus/pull/658

### Todo 
- [x] File download from encryptable/row and encryptable/show when clicking the button in row or show view -> File is correctly attached to the encryptable. Only the path for downloading the file is missing. This must be done here: 1. [row.js](https://github.com/puzzle/cryptopus/blob/feature/657/file-sharing/frontend/app/components/encryptable/row.js#L120), 2. [show.js](https://github.com/puzzle/cryptopus/blob/feature/657/file-sharing/frontend/app/components/encryptable/show.js#L42)
- [x] Fix bug when downloading file from encryptable/show and reloading that name is not filled out
- [x] Check for other data types -> The specs and manual tests were made with plain text files (.txt). Image uploads are currently not working, maybe this must be fixed. Check also .pdf files
- [x] Check if the validation for the uploaded file is working (not too big and not empty)
- [x] Fix this spec: [Order of the encryptables](https://github.com/puzzle/cryptopus/blob/feature/657/file-sharing/spec/controllers/api/teams_controller_spec.rb#L182) -> The encryptables in the inbox folder are ordered after created_at. This is working in the browser, but somehow not in this spec (maybe nowhere in the backend...)
- [x] Create component specs for the new UI features
- [x] Update specs in rails for the new features (encryptables_controller)
- [x] Disable rubocop in encryptable.rb:73
- [x] Show Badge on Personal team to show number of unread transfered files "bob (42)"
- [x] Create/check Ticket for credential sharing -> [New Ticket](https://github.com/puzzle/cryptopus/issues/688)
- [x] Fix notification when file transferred successfully
- [x] Fix system specs in pipeline

### Optional
- [ ] Display inbox folder at the top of the users personal team
- [ ] Don't allow user to rename inbox folder (remove is not a problem, because we generate an inbox folder if he isn't existing)

**Comment by lkleisa** [comment]
Badge is working, but only one time, then if you show one transferred file, the request for getting the amount of unread transferred files is not done again because we only fetch one time the teams for the side nav bar.
