### ISSUE TITLE
Switch to Pg_Search

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#663]
Because we use now PostgreSQL as db in production, we want to switch from plain sql search to [pg_search](https://github.com/Casecommons/pg_search)

https://codimd.puzzle.ch/qKQ9PTSaT5il9pQeq0oVdQ?view#Pg_Search

**Comment by MarcEgliP** [comment]
Vorgehen:
- [ ] Informieren was die pg_search ist, unter diesem Ticket kurz dokumentieren
- [ ] Tutorial zur Implementierung suchen, wenn möglich gerade mit Rails
- [ ] Implementierung umsetzen => Wenn nötig Branch der Studies zur Hand nehmen
- [ ] Tests implementieren
- [ ] Rebasen und Pullrequest stellen

**Comment by MarcEgliP** [comment]
Stand des Tickets:

- Das PgSearch Modul aus dem pg_search-gem wird nun sowohl bei einer postgres Datenbank, wie auch bei einer anderen Datenbank bei den Models team, folder und encryptable inkludiert.

- Auf dem Branch selbst wurde die Konfiguration der Datenbank zu einer Postgres Datenbank geändert, somit kann die Funktionalität direkt während des Entwickelns getestet werden

# Todo

Die PgSearch muss nun in die Search-Methode von Cryptopus eingebaut werden, allerdings nur, wenn wir auch wirklich die Postgres Datenbank brauchen

**Comment by MarcEgliP** [comment]
## Strategie 21.007.2023
- [ ] Matching Teams zurückgeben
- [ ] Tests schreiben
- [ ] Zum Review freigeben => Wenn möglich noch abschliessen

**Comment by MarcEgliP** [comment]
Update zum Ticket:

- Wir verwenden Scope_Search, um pro Tabelle die Ergebnisse zu holen welche der User auch wirklich abrufen darf
- Die lokale Entwicklungsumgebung für postgres wurde wieder abgebaut allerdings steht dafür allzeit ein eigenes docker-compose.yml in den Konfigurationsfiles bereit.
- Die Suche wird von der SearchStrategy Klasse gehandelt welche wiederum eine Unterklasse PGSearching und SQSearch enthält, beide besitzen je eine search Methode, welche unterschiedlich vorgeht.

## TODO:

- [ ] Feedback von @mtnstar einholen
- [ ] Feedback implementieren
- [ ] Mergen
