### ISSUE TITLE
ENCRYPTABLES: Finish recrypt

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#701]
Recrypt feature is implemented and can be merged soon: https://github.com/puzzle/cryptopus/pull/625

Based on Luca's IPA: https://github.com/puzzle-bbt/docs/blob/master/ipa/2022-lbu/ipa.md

# ToDo

- [x] Study PR
- [x] Rebase to current master
- [x] Make it working
- [x] Write tests
- [x] Smoke Testing
  - [x] Check file transfer
- [x] Fix file transfer
  - [x] Encrypt transferred encryptables on personal team click
  - [x] Write tests for this
- [x] Remove Crypto::Symmetric::Aes256 in transfer specs
- [x] Sync with @mtnstar and add some additional tasks if needed
- [x] Do extensive testing
- [x] Update Version, Changelog
- [x] Implement PR feedback
- [x] Sync with UX for green lock icon
- [x] Fix rubocop offense
- [ ] Implement new feedback
- [ ] Check for notification for file transfer

**Comment by lkleisa** [comment]
I start with taking the changes of Luca to a new branch #728. Now, there are some changes, which need more work, I will do that on Wednesday.

**Comment by lkleisa** [comment]
New tests are added, now smoke testing is needed on monday
