### ISSUE TITLE
Remove ose secret from ccli

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#706]
In [Ticket 683](https://github.com/puzzle/cryptopus/issues/683), we completely removed Encryptable::OseSecret from cryptopus. Now, there is also a ccli for cryptopus and also there should we remove the ose secret. 

### Todo
- [x] Checkout ccli (https://github.com/puzzle/ccli/)
- [ ] Get familiar with ccli
- [ ] Remove ose secret everywhere
- [ ] Smoke testing
