### ISSUE TITLE
Find difference file sharing and attachment

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#714]
Since the #658 file sharing, we disable rubocop with all offenses in models/encryptable.rb. This because we can't use .blank on non utf-8 files. Now, value.nil? || value.empty? is not that beautiful. Replace this with a more beautiful solution. 

# Todo
- [x] Find solution
- [x] Write test with full image

The following was found:

- Inside the file: "aes256.rb" we force_encode our ASCII Code to UTF-8
- If we change the force_encode to ASCII-8BIT the file sharing works perfectly and the .blank? too
- The pipeline failed because of the node version but this should be resolved by the branch #719 which is now merged.

**Comment by lkleisa** [comment]
The problem is the following:
In backend, we have the in encrpytable.rb model the method `encrypt_attr`, which encrypts encryptables. So far so good. This method only encrypts the cleartext_value, if cleartext_value is not blank. So it can't be nil or empty. Nil? and empty? can be simplified in rails with .blank?. The problem is here, that if cleartext_value is "" empty string, .blank throws error.

**Comment by MarcEgliP** [comment]
Planung:

- [ ] Nötige files ausfindig machen und in IDEA öffnen
- [ ] Fehler Rekonstruieren
- [ ] Fehler Beheben (Google zur Hilfe ziehen)
