### ISSUE TITLE
CCLI: Improvements Concept

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#720]
a couple of years ago we introduced the 'cryptopus command line client' `ccli`.

https://github.com/puzzle/ccli

with this ticket, some ideas for improvements around it should be specified. in general, how to make it more user friendly?

- make it easy to copy the ccli command for accessing an encryptable or just a single attribute?

# ToDo

- [x] familiarize your-self with ccli
- [x] finish ose secrets #706 
- [x] make a concept with suggestions
- [x] create follow up tickets for implementation

Follow up ticket -> [Ticket 726](https://github.com/puzzle/cryptopus/issues/726)

**Comment by lkleisa** [comment]
# Concept 
### Suggestion 1

![Image](https://github.com/puzzle/cryptopus/assets/68543649/eb97635c-2733-47e7-885f-189f9a38a32a)


![Image](https://github.com/puzzle/cryptopus/assets/68543649/7532bd63-6502-485d-ba65-234d6ec7bf9a)

### Suggestion 2


![Image](https://github.com/puzzle/cryptopus/assets/68543649/79a28396-bd13-4609-aa1c-576de35cbb57)



![Image](https://github.com/puzzle/cryptopus/assets/68543649/ec192a92-a830-47b6-b754-ff57ecb53c6d)
